OBJS = edccchk.o
CC = x86_64-pc-mingw64-gcc
DEBUG = -g
CFLAGS = -Wall -O3 -W -static -std=gnu99 -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)
LIBS = 

edccchk.exe : $(OBJS)
	$(CC) $(LFLAGS) $(LIBS) $(OBJS) -o edccchk.exe

edccchk.o : edccchk.c common.h banner.h version.h
	$(CC) $(CFLAGS) edccchk.c

clean:
	\rm *.o edccchk.exe

tar:
	zip -9 edccchk-src.zip banner.h common.h edccchk.c LICENSE Makefile README.md version.h

bindist : edccchk
	zip -9 edccchk-bin-win64.zip edccchk.exe LICENSE README.md
